### PR TITLE
Remove R, reorganize, improve documentation

### PR DESCRIPTION
**Pull request by zmbc**

### CODE REVIEW

**Review by aflaxman — APPROVED** [review]
README.md changes look good.  If you want careful review of specific notebooks please call them out --- I did not even try to check the ones with >100 lines of changes.

**Comment by zmbc** [comment]
@aflaxman There should not be any notebooks with >100 lines of changes outside of the `diagnostics` directory (which are just execution outputs and don't need code review unless you'd like to look at how a model ran).

**Review by patricktnast — APPROVED** [review]
I reviewed everything outside of the splink reports and diagnostics notebooks. Seems fairly straightforward to me.

As a general note, I think it would help the readability of these PRs a lot if you could separate the "reviewable" changes from outputs (i.e. generated notebooks and splink reports) in some way; Assuming that versioning the outputs in this repository in the way you're doing is important to you, the easiest thing to do is either highlight specific commits/groups of commits to review or submit separate PRs.

**Comment by zmbc** [comment]
Thanks @patricktnast! I think there's a larger discussion to be had around best practices for work like this, but I'll definitely try to make this clearer in the future!

**Pull request merged**
